### ISSUE TITLE
Java Heap Space in case the logs are really big

### ISSUE THREAD

**Issue by surli** [Spirals-Team/jtravis#18]
Just got the following stack trace:
```
22:07:43.831 [main] DEBUG fr.inria.jtravis.helpers.LogHelper - Get request to :https://api.travis-ci.org/job/333285507/log done after 1153 ms
Exception in thread "main" com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 16 column 2437850 path $.log_parts[0].content to Json
        at com.google.gson.JsonParser.parse(JsonParser.java:88)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at fr.inria.jtravis.helpers.AbstractHelper.getJsonFromStringContent(AbstractHelper.java:129)
        at fr.inria.jtravis.helpers.EntityHelper.getEntityFromUri(EntityHelper.java:36)
        at fr.inria.jtravis.helpers.LogHelper.from(LogHelper.java:23)
        at fr.inria.jtravis.entities.Job.fetchLog(Job.java:160)
        at fr.inria.jtravis.entities.Job.getLog(Job.java:172)
        at fr.inria.spirals.repairnator.scanner.ProjectScanner.testBuild(ProjectScanner.java:311)
        at fr.inria.spirals.repairnator.scanner.ProjectScanner.getBuildToBeInspected(ProjectScanner.java:224)
        at fr.inria.spirals.repairnator.scanner.ProjectScanner.getListOfBuildsFromRepo(ProjectScanner.java:212)
        at fr.inria.spirals.repairnator.scanner.ProjectScanner.getListOfBuildsToBeInspectedFromProjects(ProjectScanner.java:162)
        at fr.inria.spirals.repairnator.scanner.Launcher.runScanner(Launcher.java:228)
        at fr.inria.spirals.repairnator.scanner.Launcher.mainProcess(Launcher.java:203)
        at fr.inria.spirals.repairnator.scanner.Launcher.main(Launcher.java:331)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1003)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
```

**Comment by surli** [comment]
This actually happened because a lot of builds where scanned in repairnator. A first way to prevent this is to use more heap space (with `Xmx` argument). We can also look on a way to free some memory by releasing the pointer on logs when needed.
